### ISSUE TITLE
failed to initialize build cache at /root/Library/Caches/go-build: mkdir /root: read-only file system

### ISSUE THREAD

**Issue by gedw99** [titpetric/task-ui#2]
If I run this using task from Terminal it works.

But when run from task-ui it fails.

Not quite sure what's going on yet... 

I am NOT running inside docker BTW. 
Does this automatically invoke docker ?

```sh
go version go1.22.1 darwin/arm64
```

Task-UI:

```sh
task: [hot] go build -o ./webui_bin cmd/webui/main.go
failed to initialize build cache at /root/Library/Caches/go-build: mkdir /root: read-only file system
task: Failed to run task "hot": exit status 1
```

Taskfile.yml:

```yaml

# https://taskfile.dev

version: "3"

interval: 100ms

vars:
  NAME: "webui"
  BIN_NAME: "{{.NAME}}_bin"
  VERSION:
    sh: cat library/package.json| jq -r .version

  hot:
    desc: Server hot reload

    sources:
      - "**/*.go"
      - "webui/static/**/*"
      - "{{.NAME}}/static/**/*"
    
    cmds:
      #- go mod tidy
      - go build -o ./{{.BIN_NAME}} cmd/{{.NAME}}/main.go
      - ./{{.BIN_NAME}}


  default:
    deps:
      - hot
    silent: false

```
